---
title: "CDISC Pilot: Summary of Demographic and Baseline Characteristics"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
    toc_float: true
---

The Pilot 1 Team generated the below output using R and it was delivered to the FDA. You can find the source code that generated this output [here](https://github.com/RConsortium/submissions-pilot1/blob/main/vignettes/tlf-demographic.Rmd) and a deeper dive of the process [here](https://rconsortium.github.io/submissions-pilot1/articles/tlf-demographic.html).  We delivered the identical output with the R generated ADaM.

```{r, echo = FALSE, message = FALSE}
# Initiate start-up file
source(file.path(rprojroot::find_root("DESCRIPTION"), "inst/startup.R"))
```

```{r, echo = FALSE, message = FALSE}
# Working directory requires write permission
if (file.access(".", 2) != 0) {
  warning(
    "The working directory '", normalizePath("."), "' is not writable.\n",
    "Please change it to a location with write permission."
  )
}
```

```{r, echo = FALSE, message = FALSE}
# CRAN package, please using install.packages() to install
library(haven)
library(dplyr)
library(rtables)

# Propitiatory Package, please refer appendix of ADRG to install
library(pilot1wrappers)
```


```{r, echo = FALSE}
adsl <- read_xpt(file.path(path$adam, "adsl.xpt"))
adsl_labels <- var_labels(adsl)
```

```{r, echo = FALSE}
adsl <- adsl %>%
  dplyr::filter(
    STUDYID == "CDISCPILOT01",
    ITTFL == "Y"
  ) %>%
  dplyr::mutate(
    TRT01P = factor(TRT01P, levels = c("Placebo", "Xanomeline Low Dose", "Xanomeline High Dose")),
    AGEGR1 = factor(AGEGR1, levels = c("<65", "65-80", ">80")),
    RACE = factor(RACE, levels = c("WHITE", "BLACK OR AFRICAN AMERICAN", "AMERICAN INDIAN OR ALASKA NATIVE"))
  )
```

```{r, echo = FALSE}
# Table layout
vars <- c("AGE", "AGEGR1", "RACE", "HEIGHTBL", "WEIGHTBL", "BMIBL", "MMSETOT")
lyt <- basic_table(
  title = "Protocol: CDISCPILOT01",
  subtitles = "Population: Intent-to-Treat",
  main_footer = paste0("Program: tlf_demographic.Rmd \n", Sys.time())
) %>%
  split_cols_by("TRT01P") %>%
  add_colcounts() %>%
  analyze(vars, function(x, ...) {
    if (is.numeric(x)) {
      in_rows(
        "Mean (sd)" = c(mean(x), sd(x)),
        "Median" = median(x),
        "Min - Max" = range(x),
        .formats = c("xx.xx (xx.xx)", "xx.xx", "xx.xx - xx.xx")
      )
    } else if (is.factor(x) || is.character(x)) {
      in_rows(.list = list_wrap_x(table)(x))
    } else {
      stop("type not supproted")
    }
  },
  var_labels = adsl_labels[vars]
  )

# Table build
tbl <- build_table(lyt, adsl)

tbl
```
 





