---
title: "CDISC Pilot: Primary Endpoint Analysis: ADAS Cog (11) - Change from Baseline to Week 24 - LOCF"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
    toc_float: true
---

```{r, message = FALSE}
# Initiate start-up file
source(file.path(rprojroot::find_root("DESCRIPTION"), "inst/startup.R"))
```

```{r setup, message=FALSE}
library(dplyr)
library(Tplyr)
library(pilot1wrappers)
```

# Step 1: Read in data

```{r}
adas  <- haven::read_xpt(file.path(path$adam, "adadas.xpt")) 
```

## Step 2: Data preparation
```{r}
adas <- adas %>%
  filter(
    EFFFL == "Y",
    ITTFL=='Y',
    PARAMCD == 'ACTOT',
    ANL01FL == 'Y'
  )
```

## Step 3: Descriptive Statistics of Endpoint Variable
```{r}
t <- tplyr_table(adas, TRTP) %>% 
  set_desc_layer_formats(
    'n' = f_str('xx', n),
    'Mean (SD)' = f_str('xx.x (xx.xx)', mean, sd),
    'Median (Range)' = f_str('xx.x (xxx;xx)', median, min, max)
  ) %>% 
  add_layer(
    group_desc(AVAL, where= AVISITN ==  0, by = "Baseline")
  ) %>% 
  add_layer(
    group_desc(AVAL, where= AVISITN == 24, by = "Week 24")
  ) %>% 
  add_layer(
    group_desc(CHG,  where= AVISITN == 24, by = "Change from Baseline")
  )
  
sum_data <- t %>% 
  build() %>% 
  nest_rowlabels() %>% 
  select(-starts_with('ord'))
```
 
## Step 4: Statistical Summaries 

```{r}
model_portion <- efficacy_models(adas, 'CHG', 24)
```

## Step 4: Output

```{r}
# Output .out file 
tbl %>%
  toString() %>%
  writeLines(con = file.path(path$output, "tlf-demographic.out"))
```




