---
# Source: https://github.com/pharmaverse/admiralci
# Common workflows designed for Admiral
# but can be easily used by any other R package
name: CI Workflows


on:
  # 'workflow_dispatch' gives you the ability
  # to run this workflow on demand, anytime
  workflow_dispatch:
  # 'push' events are triggered when commits
  # are pushed to one of these branches
  push:
    branches:
      - main
  # 'pull_request' events are triggered when PRs are
  # created against one of these target branches.
  pull_request:
    branches:
      - main
  # 'release' events are triggered when...
  # you guessed it - when releases are made.
  release:
    types: [published]


# Docs on concurrency:
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: admiral-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Code Style
    uses: pharmaverse/admiralci/.github/workflows/style.yml@main
    if: github.event_name == 'pull_request'
    with:
      r-version: "4.2"
  docs:
    name: Documentation
    uses: pharmaverse/admiralci/.github/workflows/pkgdown.yml@main
    if: github.event_name == 'push'
    with:
      r-version: "4.2"
      # Whether to skip multiversion docs
      # Note that if you have multiple versions of docs,
      # your URL links are likely to break due to path changes
      skip-multiversion-docs: false
  linter:
    name: Lint
    uses: pharmaverse/admiralci/.github/workflows/lintr.yml@main
    if: github.event_name == 'pull_request'
    with:
      r-version: "4.2"
  links:
    name: Links
    uses: pharmaverse/admiralci/.github/workflows/links.yml@main
    if: >
      github.event_name == 'push' || github.event_name == 'pull_request'
  man-pages:
    name: Man Pages
    uses: pharmaverse/admiralci/.github/workflows/man-pages.yml@main
    if: github.event_name == 'pull_request'
    with:
      r-version: "4.2"
